P2_MVC/src/Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

P2_MVC/src/Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Welcome()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

P2_MVC/src/Web/Controllers/QuoteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace dotnet_mvc.Controllers
{
    public class QuoteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }   
        public IActionResult ShowText()
        {
            return Content("Text Display...");
        }
        public IActionResult ShowJSON()
        {
            return Json(new { Text = "JSON", Description = "JSON object Display..." });
            //return Json(new { name = "favorite quote", quote = "This is my favorite quote." });
        }
        public IActionResult ShowHTML()
        {
            var h = "<!DOCTYPE html>" +
                     "<html>" +
                     "<body>" +
                     "An awesome quote. Note return path has to use the name of the controller." +
                     "<br><br> "+"</body></html>";
            return Content(h, "text/html");
        }

        public IActionResult ShowView()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

P2_MVC/src/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

P2_MVC/src/Web/Views/Home/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome to my page!";
}
<h1>@ViewData["Title"]</h1>

<p>Welcome to this page.  <br />
    Thank You, Harika Naidu</p>

P2_MVC/src/Web/Views/Quote/Index.cshtml
@{
    ViewData["Title"] = "Quote Home Page";
}

<div class="text-center">
    <h1 class="display-4">Quotes</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <br>
    <ul>
        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="ShowText">Respond with Text</a></li>
        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="ShowJSON">Respond with JSON</a></li>
        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="ShowHTML">Respond with HTML</a></li>
        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="ShowView">Respond with a view</a></li>
    </ul>
</div>

P2_MVC/src/Web/Views/Quote/ShowHTML.cshtml
@{
    ViewData["Title"] = "Quote HTML Page";
}
<h1>@ViewData["Title"]</h1>

<p>This is Quote controller HTML Page.</p>

P2_MVC/src/Web/Views/Quote/ShowJSON.cshtml
@{
    ViewData["Title"] = "Quote JSON Page";
}
<h1>@ViewData["Title"]</h1>

<p>This is Quote controller JSON Page.</p>

P2_MVC/src/Web/Views/Quote/ShowText.cshtml
@{
    ViewData["Title"] = "Quote TEXT Page";
}
<h1>@ViewData["Title"]</h1>

<p>This is Quote Controller TEXT Page.</p>

P2_MVC/src/Web/Views/Quote/ShowView.cshtml
@{
    ViewData["Title"] = "Quote View Page";
}
<h1>@ViewData["Title"]</h1>

<p>Great minds discuss ideas; average minds discuss events; small minds discuss people.</p>

<a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="Index">Go Back to Quotes</a>

P2_MVC/src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Welcome">Welcome!!!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="ShowText">Text</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="ShowJSON">JSON</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="ShowHTML">HTML</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="ShowView">View!!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="Privacy">Quote Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>